### PR TITLE
Latest Changes from Cafe Repo

### PR DESCRIPTION
**Pull request by tn3rb**
this PR includes changes from the following cafe PRs:

- [Fix a Return Type Issue (#369)](https://github.com/eventespresso/cafe/pull/369)
- [EE Core v5.0 (#88)](https://github.com/eventespresso/cafe/pull/88)
- [Fix CSS Code Issue (#360)](https://github.com/eventespresso/cafe/pull/360)
- [Fix Unit Tests (#131)](https://github.com/eventespresso/cafe/pull/131)

### CODE REVIEW

**Comment by Pebblo** [comment]
Howdy @tn3rb,

This throws a fatal on core:

```
[04-Jan-2023 23:00:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method People_Admin_Page::addMetaBox() in C:\laragon\www\ee4\wp-content\plugins\eea-people-addon\admin\people\People_Admin_Page.core.php:803
Stack trace:
#0 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\admin\EE_Admin_Page.core.php(2141): People_Admin_Page->people_editor_metaboxes()
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\admin\EE_Admin_Page.core.php(700): EE_Admin_Page->_add_registered_meta_boxes()
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\admin\EE_Admin_Page_CPT.core.php(407): EE_Admin_Page->_load_page_dependencies()
#3 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\admin\EE_Admin_Page_CPT.core.php(322): EE_Admin_Page_CPT->_load_page_dependencies()
#4 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(308): EE_Admin_Page_CPT->load_page_dependencies('')
#5 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 C:\laragon\www\ee4\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 C:\laragon\www\ee4\wp-admin\admin.php(237): do_action('load-event-espr...')
#8 {main}
  thrown in C:\laragon\www\ee4\wp-content\plugins\eea-people-addon\admin\people\People_Admin_Page.core.php on line 803
```

**Comment by Pebblo** [comment]
So, cafe adds a new method which core obviously doesn't have, so I've just copied `EE_Admin_Page::addMetaBox()` into `People_Admin_Page` to make this compatible with both core and cafe.

I'm aware this latest change goes against making changes one way (Cafe to Core repos) but I wasn't sure if this was the correct way to go about fixing this, so applied it here and if this is the correct way to move forward I'll apply the same change to Cafe.

Or is it still best to apply to cafe first and then copy over again?

---

After cafe has been out a little if we update the people add-on I'm ok with bumping the min required version and removing this shim if needed.

**Comment by tn3rb** [comment]
that should be fine, sorry about that btw

**Comment by Pebblo** [comment]
Found another when testing this to do a release, if you don't have a country set on a person it threw a type error so the latest commit fixes it.

@tn3rb if the above is correct I'll package this up and port the 2 changes over to Cafe once done

**Pull request merged**
